  - name: Installing the Network Time Protocol (NTP)
    apt:
      name: chrony
      state: present
      update_cache: yes

  - name: Enable the chrony
    service:
      name: chrony.service
      state: restarted
      enabled: yes
