---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: controller
  become: true
  roles:
    - NTP
    - OpenStack
    - SQL
    - MessageQ
    - Memcached
    - Etcd
