- name: Install Message Queue
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes

- name: Starting service
  service:
    name: rabbitmq-server.service
    state: started
    enabled: true
